[package]
name = "asymmetric-key-ciphering"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes = "0.8.4"
eframe = "0.27.2"
rand = "0.8.5"
rfd = "0.14.1"
rsa = "0.9.6"
